"""The seventy-six role charters.

This file is the company's org chart, and it is deliberately data rather than
classes. A charter is *what the role is for* plus the three permission scopes
that follow from it; an agent is a row that **holds** some coverage of one or
more charters.

Separating the two is the growth mechanism (ADR-0003). All seventy-six exist
from day one. Seventeen launch agents hold them as generalists, and the company
splits its own roles onto dedicated specialists as measured load and quality
justify it — without the runtime changing at all, because agents are rows,
charters are this file, and desks are config.

Numbering follows ``docs/02-organization.md`` §4 so the two can be checked
against each other. A test asserts they agree.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from aurelis.core.enums import ModelTier
from aurelis.org.departments import Department
from aurelis.org.scopes import ReadView, ToolScope, WriteScope

__all__ = ["CHARTERS", "Charter", "Seniority", "charters_for_department"]


class Seniority(StrEnum):
    """Rank. Also how cost tracks demonstrated value: model tier follows it."""

    JUNIOR = "junior"
    SENIOR = "senior"
    LEAD = "lead"
    DIRECTOR = "director"


@dataclass(frozen=True, slots=True)
class Charter:
    """One role's full remit and the authority that follows from it."""

    charter_id: str
    number: int
    name: str
    department: Department
    remit: str
    tier: ModelTier
    seniority: Seniority = Seniority.SENIOR
    read_views: tuple[ReadView, ...] = field(default_factory=tuple)
    write_scopes: tuple[WriteScope, ...] = field(default_factory=tuple)
    tools: tuple[ToolScope, ...] = field(default_factory=tuple)
    desk_specific: bool = False
    """True when the role is meaningfully different per market. These are the
    charters that multiply across desks as the company grows."""

    deterministic: bool = False
    """True when the role is software wearing a badge. Costs nothing to run,
    and 'who computed this?' stays a checkable field rather than a guess."""


def _c(*args: object, **kwargs: object) -> Charter:
    return Charter(*args, **kwargs)  # type: ignore[arg-type]


# Common bundles, so a change to "what every agent can see" is one edit.
_BASE_VIEWS = (ReadView.COMPANY_STATE, ReadView.MISSION_BRIEF, ReadView.TASK_ASSIGNMENT)
_TALK = (ToolScope.COMMS_POST, ToolScope.COMMS_MESSAGE)
_TALK_ESCALATE = (*_TALK, ToolScope.COMMS_ESCALATE)
_SPEAK_IN_MEETINGS = (WriteScope.MESSAGE, WriteScope.MEETING_TURN, WriteScope.FORECAST)


CHARTERS: dict[str, Charter] = {
    charter.charter_id: charter
    for charter in (
        # ---------------------------------------------------------- executive
        _c(
            "exec.company_manager",
            1,
            "Company Manager (CEO)",
            Department.EXECUTIVE,
            "Company direction, the mission portfolio, final escalation, chairs the Board",
            ModelTier.HIGH,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.ORG_METRICS, ReadView.AGENT_METRICS, ReadView.PORTFOLIO_BOOK),
            (*_SPEAK_IN_MEETINGS, WriteScope.DECISION, WriteScope.TASK, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "exec.research_director",
            2,
            "Research Director (CIO)",
            Department.EXECUTIVE,
            "The research agenda: what gets studied, and how effort is allocated",
            ModelTier.HIGH,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.PRIOR_ART, ReadView.GRAVEYARD, ReadView.ORG_METRICS),
            (*_SPEAK_IN_MEETINGS, WriteScope.DECISION, WriteScope.TASK, WriteScope.HYPOTHESIS),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "exec.operations_director",
            3,
            "Operations Director",
            Department.EXECUTIVE,
            "Throughput, blockers, scheduling, department health",
            ModelTier.MID,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.ORG_METRICS, ReadView.SYSTEM_HEALTH),
            (*_SPEAK_IN_MEETINGS, WriteScope.TASK, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING),
        ),
        _c(
            "exec.mission_orchestrator",
            4,
            "Mission Orchestrator",
            Department.EXECUTIVE,
            "Decomposes missions into projects and tasks and tracks progress",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.ORG_METRICS),
            (*_SPEAK_IN_MEETINGS, WriteScope.TASK),
            (*_TALK, ToolScope.COMMS_CALL_MEETING),
        ),
        _c(
            "exec.chief_of_staff",
            5,
            "Chief of Staff / Chair",
            Department.EXECUTIVE,
            "Runs meetings: agenda, rounds, budget, minutes, action items",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.MEETING_EVIDENCE_PACK, ReadView.MEETING_TRANSCRIPT),
            (*_SPEAK_IN_MEETINGS, WriteScope.DECISION, WriteScope.TASK),
            (*_TALK, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "exec.org_development",
            6,
            "Org Development Lead",
            Department.EXECUTIVE,
            "Watches org metrics; proposes fission, fusion and hiring on evidence",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.ORG_METRICS, ReadView.AGENT_METRICS),
            (*_SPEAK_IN_MEETINGS, WriteScope.ORG_CHANGE),
            (*_TALK, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        # ------------------------------------------------- market intelligence
        _c(
            "intel.head",
            7,
            "Head of Market Intelligence",
            Department.MARKET_INTELLIGENCE,
            "Briefing quality, source coverage, desk intelligence priorities",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.DESK_OBSERVATIONS, ReadView.SOURCE_RELIABILITY),
            (*_SPEAK_IN_MEETINGS, WriteScope.BRIEFING, WriteScope.TASK, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "intel.fundamental_analyst",
            8,
            "Fundamental Analyst",
            Department.MARKET_INTELLIGENCE,
            "Financial statements, valuation, earnings, sector economics",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.DESK_OBSERVATIONS),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_FUNDAMENTALS, ToolScope.MEMORY_SEARCH),
            desk_specific=True,
        ),
        _c(
            "intel.news_analyst",
            9,
            "News Analyst",
            Department.MARKET_INTELLIGENCE,
            "Event detection, materiality, timeline reconstruction",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.SOURCE_RELIABILITY),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_NEWS, ToolScope.MEMORY_SEARCH),
            desk_specific=True,
        ),
        _c(
            "intel.sentiment_analyst",
            10,
            "Sentiment / Social Analyst",
            Department.MARKET_INTELLIGENCE,
            "Positioning, crowding, social signal with base rates attached",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.SOURCE_RELIABILITY),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_SENTIMENT),
            desk_specific=True,
        ),
        _c(
            "intel.technical_analyst",
            11,
            "Technical Analyst",
            Department.MARKET_INTELLIGENCE,
            "Price structure, trend, volatility, microstructure observation",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.DESK_OBSERVATIONS),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_OHLCV, ToolScope.ENGINE_FEATURES, ToolScope.MEMORY_SEARCH),
            desk_specific=True,
        ),
        _c(
            "intel.macro_analyst",
            12,
            "Macro Analyst",
            Department.MARKET_INTELLIGENCE,
            "Rates, growth, inflation, policy, cross-asset linkage",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.DESK_OBSERVATIONS),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_OHLCV, ToolScope.DATA_NEWS, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "intel.regime_analyst",
            13,
            "Regime Analyst",
            Department.MARKET_INTELLIGENCE,
            "Regime identification, transitions, conditional behaviour",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.DESK_OBSERVATIONS),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (
                *_TALK,
                ToolScope.DATA_OHLCV,
                ToolScope.ENGINE_FEATURES,
                ToolScope.STATS_SIGNIFICANCE,
            ),
            desk_specific=True,
        ),
        _c(
            "intel.alternative_data_analyst",
            14,
            "Alternative Data Analyst",
            Department.MARKET_INTELLIGENCE,
            "On-chain, flows, positioning, novel sources and their reliability",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.SOURCE_RELIABILITY),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.BRIEFING),
            (*_TALK, ToolScope.DATA_ONCHAIN, ToolScope.DATA_SENTIMENT),
            desk_specific=True,
        ),
        _c(
            "intel.source_reliability",
            15,
            "Source Reliability Officer",
            Department.MARKET_INTELLIGENCE,
            "Tracks every source's freshness, revisions and historical accuracy",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.SOURCE_RELIABILITY, ReadView.DESK_OBSERVATIONS),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.ALERT),
            (*_TALK, ToolScope.LEDGER_QUERY),
        ),
        # ---------------------------------------------- quantitative research
        _c(
            "research.lead",
            16,
            "Lead Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Owns a research programme, assigns work, defends findings",
            ModelTier.HIGH,
            Seniority.LEAD,
            (
                *_BASE_VIEWS,
                ReadView.HYPOTHESIS_STATEMENT,
                ReadView.EXPERIMENT_RESULT,
                ReadView.PRIOR_ART,
                ReadView.OPEN_OBJECTIONS,
            ),
            (
                *_SPEAK_IN_MEETINGS,
                WriteScope.HYPOTHESIS,
                WriteScope.FINDING,
                WriteScope.TASK,
                WriteScope.DECISION,
            ),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "research.quant",
            17,
            "Quant Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Designs and runs experiments; forms hypotheses",
            ModelTier.MID,
            Seniority.SENIOR,
            (
                *_BASE_VIEWS,
                ReadView.HYPOTHESIS_STATEMENT,
                ReadView.EXPERIMENT_DESIGN,
                ReadView.EXPERIMENT_RESULT,
                ReadView.PRIOR_ART,
            ),
            (
                *_SPEAK_IN_MEETINGS,
                WriteScope.HYPOTHESIS,
                WriteScope.EXPERIMENT_SPEC,
                WriteScope.FINDING,
                WriteScope.EVIDENCE,
            ),
            (
                *_TALK,
                ToolScope.ENGINE_BACKTEST,
                ToolScope.ENGINE_FEATURES,
                ToolScope.ENGINE_STATISTICS,
                ToolScope.MEMORY_SEARCH,
            ),
            desk_specific=True,
        ),
        _c(
            "research.statistical",
            18,
            "Statistical Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Test selection, power, multiple testing, confidence intervals",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.FINDING, WriteScope.EVIDENCE, WriteScope.OBJECTION),
            (
                *_TALK,
                ToolScope.ENGINE_STATISTICS,
                ToolScope.STATS_SIGNIFICANCE,
                ToolScope.STATS_CALIBRATION,
            ),
        ),
        _c(
            "research.backtest",
            19,
            "Backtest Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Backtest design, cost realism, walk-forward protocol",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC, WriteScope.FINDING),
            (
                *_TALK,
                ToolScope.ENGINE_BACKTEST,
                ToolScope.INTEGRITY_LEAK_SCAN,
                ToolScope.INTEGRITY_POINT_IN_TIME,
            ),
            desk_specific=True,
        ),
        _c(
            "research.simulation",
            20,
            "Simulation / Monte Carlo Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Path simulation, bootstrap, prop-rule and ruin analysis",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC, WriteScope.FINDING),
            (*_TALK, ToolScope.ENGINE_SIMULATION, ToolScope.ENGINE_STATISTICS),
        ),
        _c(
            "research.ml",
            21,
            "ML Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Learned models, feature design, purged CV, calibration",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC, WriteScope.FINDING),
            (
                *_TALK,
                ToolScope.ENGINE_FEATURES,
                ToolScope.STATS_CALIBRATION,
                ToolScope.INTEGRITY_LEAK_SCAN,
            ),
        ),
        _c(
            "research.factor",
            22,
            "Factor Researcher",
            Department.QUANTITATIVE_RESEARCH,
            "Factor construction, exposure, spanning tests",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_RESULT, ReadView.PORTFOLIO_BOOK),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC, WriteScope.FINDING),
            (*_TALK, ToolScope.ENGINE_FEATURES, ToolScope.PORTFOLIO_ATTRIBUTION),
            desk_specific=True,
        ),
        _c(
            "research.engineer",
            23,
            "Research Engineer",
            Department.QUANTITATIVE_RESEARCH,
            "Builds experiment specs, engine adapters, data pipelines and tooling",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN, ReadView.SYSTEM_HEALTH),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC),
            (*_TALK, ToolScope.ENGINE_BACKTEST, ToolScope.ENGINE_FEATURES, ToolScope.DATA_OHLCV),
        ),
        _c(
            "research.data_scientist",
            24,
            "Data Scientist",
            Department.QUANTITATIVE_RESEARCH,
            "Exploratory analysis, visualisation, anomaly surfacing",
            ModelTier.MID,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.DESK_MARKET_SNAPSHOT, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION, WriteScope.FINDING),
            (*_TALK, ToolScope.ENGINE_FEATURES, ToolScope.DATA_OHLCV),
        ),
        # -------------------------------------------------- strategy laboratory
        _c(
            "strategy.head",
            25,
            "Head of Strategy",
            Department.STRATEGY_LABORATORY,
            "The strategy portfolio and the promotion agenda; chairs Strategy Committee",
            ModelTier.HIGH,
            Seniority.DIRECTOR,
            (
                *_BASE_VIEWS,
                ReadView.STRATEGY_SPEC,
                ReadView.STRATEGY_EVIDENCE,
                ReadView.PROMOTION_GATES,
                ReadView.PORTFOLIO_BOOK,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.DECISION, WriteScope.TASK),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "strategy.architect",
            26,
            "Strategy Architect",
            Department.STRATEGY_LABORATORY,
            "Turns findings into strategy designs: entries, exits, sizing",
            ModelTier.HIGH,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.STRATEGY_SPEC, ReadView.STRATEGY_EVIDENCE, ReadView.PRIOR_ART),
            (*_SPEAK_IN_MEETINGS, WriteScope.STRATEGY_VERSION, WriteScope.HYPOTHESIS),
            (*_TALK, ToolScope.ENGINE_BACKTEST, ToolScope.MEMORY_SEARCH),
            desk_specific=True,
        ),
        _c(
            "strategy.discovery",
            27,
            "Strategy Discovery Agent",
            Department.STRATEGY_LABORATORY,
            "Systematic search over the hypothesis space for candidates",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.PRIOR_ART, ReadView.GRAVEYARD),
            (*_SPEAK_IN_MEETINGS, WriteScope.HYPOTHESIS),
            (*_TALK, ToolScope.ENGINE_FEATURES, ToolScope.MEMORY_SEARCH),
            desk_specific=True,
        ),
        _c(
            "strategy.synthesizer",
            28,
            "Strategy Synthesizer",
            Department.STRATEGY_LABORATORY,
            "Combines signals and strategies into coherent specifications",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.STRATEGY_SPEC, ReadView.STRATEGY_EVIDENCE),
            (*_SPEAK_IN_MEETINGS, WriteScope.STRATEGY_VERSION),
            (*_TALK, ToolScope.ENGINE_BACKTEST, ToolScope.PORTFOLIO_CORRELATION),
        ),
        _c(
            "strategy.critic",
            29,
            "Strategy Critic",
            Department.STRATEGY_LABORATORY,
            "Attacks the design: assumptions, fragility, hidden costs",
            ModelTier.MID,
            Seniority.SENIOR,
            (
                *_BASE_VIEWS,
                ReadView.STRATEGY_SPEC,
                ReadView.STRATEGY_EVIDENCE,
                ReadView.EXPERIMENT_RESULT,
                ReadView.OPEN_OBJECTIONS,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.OBJECTION, WriteScope.EVIDENCE),
            (
                *_TALK,
                ToolScope.ENGINE_BACKTEST,
                ToolScope.INTEGRITY_LEAK_SCAN,
                ToolScope.MEMORY_SEARCH,
            ),
        ),
        _c(
            "strategy.adversarial",
            30,
            "Adversarial Researcher",
            Department.STRATEGY_LABORATORY,
            "Actively tries to break results; hunts for the reason it is wrong",
            ModelTier.MID,
            Seniority.SENIOR,
            (
                *_BASE_VIEWS,
                ReadView.EXPERIMENT_DESIGN,
                ReadView.EXPERIMENT_RESULT,
                ReadView.OPEN_OBJECTIONS,
                ReadView.GRAVEYARD,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.OBJECTION, WriteScope.EXPERIMENT_SPEC),
            (
                *_TALK,
                ToolScope.ENGINE_BACKTEST,
                ToolScope.INTEGRITY_LEAK_SCAN,
                ToolScope.INTEGRITY_POINT_IN_TIME,
            ),
        ),
        _c(
            "strategy.replication",
            31,
            "Replication Researcher",
            Department.STRATEGY_LABORATORY,
            "Independent re-test with a deliberate declared variation",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.HYPOTHESIS_STATEMENT, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.REPLICATION, WriteScope.EXPERIMENT_SPEC),
            (*_TALK, ToolScope.ENGINE_BACKTEST, ToolScope.ENGINE_STATISTICS),
        ),
        _c(
            "strategy.robustness",
            32,
            "Robustness Researcher",
            Department.STRATEGY_LABORATORY,
            "Parameter, period, universe, cost and regime stress grids",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.STRATEGY_SPEC, ReadView.EXPERIMENT_RESULT),
            (*_SPEAK_IN_MEETINGS, WriteScope.EXPERIMENT_SPEC, WriteScope.OBJECTION),
            (*_TALK, ToolScope.ENGINE_BACKTEST, ToolScope.ENGINE_SIMULATION),
        ),
        _c(
            "strategy.validation",
            33,
            "Validation Researcher",
            Department.STRATEGY_LABORATORY,
            "Runs the promotion gates and owns the out-of-sample request",
            ModelTier.MID,
            Seniority.LEAD,
            (
                *_BASE_VIEWS,
                ReadView.STRATEGY_SPEC,
                ReadView.STRATEGY_EVIDENCE,
                ReadView.PROMOTION_GATES,
                ReadView.OPEN_OBJECTIONS,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.PROMOTION_GATE),
            (*_TALK, ToolScope.ENGINE_STATISTICS, ToolScope.STATS_SIGNIFICANCE),
        ),
        # ------------------------------------------------------ portfolio & risk
        _c(
            "risk.chief",
            34,
            "Chief Risk Officer",
            Department.PORTFOLIO_AND_RISK,
            "Risk authority: limits, veto, kill switches; chairs Risk Committee",
            ModelTier.HIGH,
            Seniority.DIRECTOR,
            (
                *_BASE_VIEWS,
                ReadView.PORTFOLIO_BOOK,
                ReadView.RISK_LIMITS,
                ReadView.EXPOSURE_SNAPSHOT,
                ReadView.POSITION_STATE,
            ),
            (
                *_SPEAK_IN_MEETINGS,
                WriteScope.RISK_ASSESSMENT,
                WriteScope.RISK_LIMIT,
                WriteScope.DECISION,
                WriteScope.ALERT,
            ),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.PORTFOLIO_CORRELATION),
        ),
        _c(
            "risk.manager",
            35,
            "Risk Manager",
            Department.PORTFOLIO_AND_RISK,
            "Per-strategy and per-desk risk assessment on every proposal",
            ModelTier.MID,
            Seniority.SENIOR,
            (
                *_BASE_VIEWS,
                ReadView.PORTFOLIO_BOOK,
                ReadView.RISK_LIMITS,
                ReadView.EXPOSURE_SNAPSHOT,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.RISK_ASSESSMENT, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.PORTFOLIO_CORRELATION),
            desk_specific=True,
        ),
        _c(
            "risk.portfolio_manager",
            36,
            "Portfolio Manager",
            Department.PORTFOLIO_AND_RISK,
            "Portfolio construction from approved strategy signals",
            ModelTier.MID,
            Seniority.LEAD,
            (
                *_BASE_VIEWS,
                ReadView.PORTFOLIO_BOOK,
                ReadView.EXPOSURE_SNAPSHOT,
                ReadView.RISK_LIMITS,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.PORTFOLIO_ALLOCATION, WriteScope.TRADE_PROPOSAL),
            (*_TALK, ToolScope.PORTFOLIO_CORRELATION, ToolScope.PORTFOLIO_ATTRIBUTION),
        ),
        _c(
            "risk.exposure_analyst",
            37,
            "Exposure Analyst",
            Department.PORTFOLIO_AND_RISK,
            "Gross, net, concentration, sector, desk and factor exposure",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.PORTFOLIO_BOOK, ReadView.EXPOSURE_SNAPSHOT),
            (*_SPEAK_IN_MEETINGS, WriteScope.FINDING, WriteScope.ALERT),
            (*_TALK, ToolScope.PORTFOLIO_ATTRIBUTION),
        ),
        _c(
            "risk.correlation_analyst",
            38,
            "Correlation Analyst",
            Department.PORTFOLIO_AND_RISK,
            "Inter-strategy correlation, drawdown interaction, diversification",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.PORTFOLIO_BOOK, ReadView.STRATEGY_EVIDENCE),
            (*_SPEAK_IN_MEETINGS, WriteScope.FINDING, WriteScope.OBJECTION),
            (*_TALK, ToolScope.PORTFOLIO_CORRELATION, ToolScope.ENGINE_STATISTICS),
        ),
        _c(
            "risk.capital_allocation",
            39,
            "Capital Allocation Analyst",
            Department.PORTFOLIO_AND_RISK,
            "Allocation across strategies and desks; capacity analysis",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.PORTFOLIO_BOOK, ReadView.RISK_LIMITS),
            (*_SPEAK_IN_MEETINGS, WriteScope.PORTFOLIO_ALLOCATION),
            (*_TALK, ToolScope.PORTFOLIO_ATTRIBUTION, ToolScope.ENGINE_SIMULATION),
        ),
        _c(
            "risk.stress_testing",
            40,
            "Stress Testing Analyst",
            Department.PORTFOLIO_AND_RISK,
            "Scenario and historical stress, tail behaviour, liquidity shock",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.PORTFOLIO_BOOK, ReadView.EXPOSURE_SNAPSHOT),
            (*_SPEAK_IN_MEETINGS, WriteScope.FINDING, WriteScope.ALERT),
            (*_TALK, ToolScope.ENGINE_SIMULATION),
        ),
        # ------------------------------------------------------ trading operations
        _c(
            "trading.head",
            41,
            "Head of Trading",
            Department.TRADING_OPERATIONS,
            "Operational integrity of everything that reaches a broker",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.APPROVED_INSTRUCTIONS, ReadView.POSITION_STATE),
            (*_SPEAK_IN_MEETINGS, WriteScope.DECISION, WriteScope.ALERT),
            (*_TALK_ESCALATE,),
        ),
        _c(
            "trading.market_setup",
            42,
            "Market Setup Analyst",
            Department.TRADING_OPERATIONS,
            "Whether current conditions suit an approved strategy",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.APPROVED_INSTRUCTIONS, ReadView.DESK_MARKET_SNAPSHOT),
            (*_SPEAK_IN_MEETINGS, WriteScope.MARKET_OBSERVATION),
            (*_TALK, ToolScope.DATA_OHLCV),
            desk_specific=True,
        ),
        _c(
            "trading.planner",
            43,
            "Trade Planner",
            Department.TRADING_OPERATIONS,
            "Turns target exposure into an executable plan",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.APPROVED_INSTRUCTIONS, ReadView.POSITION_STATE),
            (*_SPEAK_IN_MEETINGS, WriteScope.TRADE_PROPOSAL),
            (*_TALK,),
        ),
        _c(
            "trading.approval",
            44,
            "Trade Approval Agent",
            Department.TRADING_OPERATIONS,
            "Final gate: checks the approval chain, limits and halts",
            ModelTier.LOW,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.APPROVED_INSTRUCTIONS, ReadView.RISK_LIMITS),
            (WriteScope.TRADE_APPROVAL, WriteScope.MESSAGE, WriteScope.ALERT),
            (*_TALK_ESCALATE,),
        ),
        _c(
            "trading.execution",
            45,
            "Execution Agent",
            Department.TRADING_OPERATIONS,
            "Submits orders through the broker adapter, and nothing else",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.APPROVED_INSTRUCTIONS),
            (WriteScope.ORDER, WriteScope.MESSAGE),
            (ToolScope.BROKER_SUBMIT, ToolScope.COMMS_MESSAGE),
        ),
        _c(
            "trading.position_monitor",
            46,
            "Position Monitor",
            Department.TRADING_OPERATIONS,
            "Live positions, drawdown, divergence from expectation",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.POSITION_STATE, ReadView.RISK_LIMITS),
            (*_SPEAK_IN_MEETINGS, WriteScope.ALERT),
            (*_TALK_ESCALATE,),
        ),
        _c(
            "trading.post_trade",
            47,
            "Post-Trade Analyst",
            Department.TRADING_OPERATIONS,
            "Slippage, cost attribution, backtest-vs-live gap",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.POSITION_STATE, ReadView.STRATEGY_EVIDENCE),
            (*_SPEAK_IN_MEETINGS, WriteScope.FINDING, WriteScope.EVIDENCE),
            (*_TALK, ToolScope.ENGINE_STATISTICS),
        ),
        # ------------------------------------------------------ audit & governance
        _c(
            "audit.chief",
            48,
            "Chief Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Independent challenge authority across the whole company",
            ModelTier.HIGH,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.OBJECTION, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.LEDGER_QUERY),
        ),
        _c(
            "audit.research",
            49,
            "Research Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Preregistration compliance, HARKing, cherry-picking, spec drift",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.OBJECTION),
            (*_TALK_ESCALATE, ToolScope.LEDGER_QUERY),
        ),
        _c(
            "audit.data",
            50,
            "Data Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Timestamps, revisions, survivorship, point-in-time correctness",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.OBJECTION),
            (*_TALK_ESCALATE, ToolScope.INTEGRITY_POINT_IN_TIME, ToolScope.DATA_OHLCV),
        ),
        _c(
            "audit.backtest",
            51,
            "Backtest Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Look-ahead, cost realism, liquidity assumptions, leakage",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.OBJECTION),
            (*_TALK_ESCALATE, ToolScope.INTEGRITY_LEAK_SCAN, ToolScope.ENGINE_BACKTEST),
        ),
        _c(
            "audit.execution",
            52,
            "Execution Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Approval chains, limit breaches, unapproved orders",
            ModelTier.LOW,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.LEDGER_QUERY),
        ),
        _c(
            "audit.agent_behavior",
            53,
            "Agent Behavior Auditor",
            Department.AUDIT_AND_GOVERNANCE,
            "Role-boundary violations, fabricated figures, unsupported claims",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING, ReadView.AGENT_METRICS),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.LEDGER_QUERY),
        ),
        # ------------------------------------------------------ knowledge & memory
        _c(
            "knowledge.chief",
            54,
            "Chief Knowledge Officer",
            Department.KNOWLEDGE_AND_MEMORY,
            "What the company knows, and how confident it is entitled to be",
            ModelTier.MID,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.INSTITUTIONAL_MEMORY, ReadView.GRAVEYARD, ReadView.PRIOR_ART),
            (*_SPEAK_IN_MEETINGS, WriteScope.LESSON, WriteScope.KNOWLEDGE_EDGE),
            (*_TALK, ToolScope.MEMORY_SEARCH, ToolScope.LEDGER_QUERY),
        ),
        _c(
            "knowledge.memory_keeper",
            55,
            "Institutional Memory Keeper",
            Department.KNOWLEDGE_AND_MEMORY,
            "Lessons learned, standing rules, what not to repeat",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.INSTITUTIONAL_MEMORY, ReadView.MEETING_TRANSCRIPT),
            (*_SPEAK_IN_MEETINGS, WriteScope.LESSON),
            (*_TALK, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "knowledge.archivist",
            56,
            "Research Archivist",
            Department.KNOWLEDGE_AND_MEMORY,
            "Every experiment, result and document, retrievable",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.INSTITUTIONAL_MEMORY, ReadView.EXPERIMENT_RESULT),
            (WriteScope.MESSAGE, WriteScope.KNOWLEDGE_EDGE),
            (*_TALK, ToolScope.MEMORY_SEARCH, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "knowledge.strategy_registrar",
            57,
            "Strategy Registrar",
            Department.KNOWLEDGE_AND_MEMORY,
            "Strategy registry, versions, states, promotion history",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.STRATEGY_SPEC, ReadView.PROMOTION_GATES),
            (WriteScope.MESSAGE, WriteScope.KNOWLEDGE_EDGE),
            (*_TALK, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "knowledge.hypothesis_ledger",
            58,
            "Hypothesis Ledger Keeper",
            Department.KNOWLEDGE_AND_MEMORY,
            "Every hypothesis and trial ever registered, including the dead",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.PRIOR_ART, ReadView.GRAVEYARD),
            (WriteScope.MESSAGE, WriteScope.KNOWLEDGE_EDGE),
            (*_TALK, ToolScope.LEDGER_QUERY, ToolScope.MEMORY_SEARCH),
            deterministic=True,
        ),
        _c(
            "knowledge.graph_curator",
            59,
            "Knowledge Graph Curator",
            Department.KNOWLEDGE_AND_MEMORY,
            "Nodes, edges, dependency and contradiction structure",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.INSTITUTIONAL_MEMORY, ReadView.PRIOR_ART),
            (*_SPEAK_IN_MEETINGS, WriteScope.KNOWLEDGE_EDGE),
            (*_TALK, ToolScope.MEMORY_SEARCH),
        ),
        # ------------------------------------------------------------ infrastructure
        _c(
            "infra.head",
            60,
            "Head of Infrastructure",
            Department.INFRASTRUCTURE,
            "Platform health, capacity, reliability",
            ModelTier.MID,
            Seniority.LEAD,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH),
            (*_SPEAK_IN_MEETINGS, WriteScope.ALERT, WriteScope.TASK),
            (*_TALK_ESCALATE,),
        ),
        _c(
            "infra.data_systems",
            61,
            "Data Systems Engineer",
            Department.INFRASTRUCTURE,
            "Ingestion, validation, storage, freshness, backfills",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH, ReadView.SOURCE_RELIABILITY),
            (*_SPEAK_IN_MEETINGS, WriteScope.ALERT),
            (*_TALK, ToolScope.DATA_OHLCV, ToolScope.INTEGRITY_POINT_IN_TIME),
        ),
        _c(
            "infra.compute",
            62,
            "Compute Manager",
            Department.INFRASTRUCTURE,
            "Job scheduling, resource limits, queue health",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH),
            (WriteScope.MESSAGE, WriteScope.ALERT, WriteScope.TASK),
            (*_TALK,),
            deterministic=True,
        ),
        _c(
            "infra.agent_runtime",
            63,
            "Agent Runtime Manager",
            Department.INFRASTRUCTURE,
            "Agent lifecycle, stuck workers, restarts, model routing",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH, ReadView.AGENT_METRICS),
            (WriteScope.MESSAGE, WriteScope.ALERT),
            (*_TALK,),
            deterministic=True,
        ),
        _c(
            "infra.observability",
            64,
            "Observability Engineer",
            Department.INFRASTRUCTURE,
            "Metrics, alerting, dashboards feeding the station",
            ModelTier.LOW,
            Seniority.JUNIOR,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH, ReadView.LEDGER),
            (WriteScope.MESSAGE, WriteScope.ALERT),
            (*_TALK, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "infra.integrations",
            65,
            "Integrations Engineer",
            Department.INFRASTRUCTURE,
            "External APIs, brokers, feeds, credentials handling",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.SYSTEM_HEALTH),
            (*_SPEAK_IN_MEETINGS, WriteScope.ALERT),
            (*_TALK, ToolScope.DATA_OHLCV),
        ),
        # ------------------------------------------------- institutional governance
        _c(
            "gov.director",
            66,
            "Governance Director",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Owns the integrity machinery; reports findings to the Board",
            ModelTier.MID,
            Seniority.DIRECTOR,
            (*_BASE_VIEWS, ReadView.LEDGER, ReadView.EVERYTHING),
            (*_SPEAK_IN_MEETINGS, WriteScope.AUDIT_RECORD, WriteScope.ALERT),
            (*_TALK_ESCALATE, ToolScope.COMMS_CALL_MEETING, ToolScope.LEDGER_QUERY),
        ),
        _c(
            "gov.registrar",
            67,
            "Registrar",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Locks and hashes preregistrations before any run",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.HYPOTHESIS_STATEMENT, ReadView.EXPERIMENT_DESIGN),
            (WriteScope.REGISTRATION, WriteScope.MESSAGE),
            (ToolScope.COMMS_MESSAGE, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "gov.custodian",
            68,
            "Custodian",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Holds sealed out-of-sample data; releases counted queries",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_DESIGN),
            (WriteScope.SEALED_QUERY, WriteScope.MESSAGE),
            (ToolScope.COMMS_MESSAGE,),
            deterministic=True,
        ),
        _c(
            "gov.evidence_officer",
            69,
            "Evidence Officer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Enforces evidence typing; rejects speculation promoted to fact",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (WriteScope.OBJECTION, WriteScope.MESSAGE),
            (ToolScope.COMMS_MESSAGE, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "gov.forecast_scorer",
            70,
            "Forecast Scorer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Collects pre-run forecasts, scores them, publishes calibration",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.AGENT_METRICS, ReadView.EXPERIMENT_RESULT),
            (WriteScope.MESSAGE,),
            (ToolScope.COMMS_MESSAGE, ToolScope.STATS_CALIBRATION),
            deterministic=True,
        ),
        _c(
            "gov.ledger_officer",
            71,
            "Ledger Officer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Verifies the hash chain, reconciles totals, reports tampering",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.LEDGER),
            (WriteScope.MESSAGE, WriteScope.ALERT, WriteScope.AUDIT_RECORD),
            (ToolScope.COMMS_MESSAGE, ToolScope.COMMS_ESCALATE, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "gov.budget_officer",
            72,
            "Budget Officer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Hierarchical budgets, dispatch refusal, spend reporting",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.ORG_METRICS, ReadView.SYSTEM_HEALTH),
            (WriteScope.MESSAGE, WriteScope.ALERT),
            (ToolScope.COMMS_MESSAGE, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "gov.provenance_officer",
            73,
            "Provenance Officer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Every figure traces to an artifact; flags orphaned numbers",
            ModelTier.NONE,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING),
            (WriteScope.OBJECTION, WriteScope.MESSAGE, WriteScope.ALERT),
            (ToolScope.COMMS_MESSAGE, ToolScope.LEDGER_QUERY),
            deterministic=True,
        ),
        _c(
            "gov.skeptic",
            74,
            "Skeptic-in-Residence",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Standing adversarial review, independent of the Strategy Lab",
            ModelTier.MID,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EVERYTHING, ReadView.GRAVEYARD),
            (*_SPEAK_IN_MEETINGS, WriteScope.OBJECTION),
            (*_TALK_ESCALATE, ToolScope.MEMORY_SEARCH),
        ),
        _c(
            "gov.replication_officer",
            75,
            "Replication Officer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Schedules and adjudicates independent replications",
            ModelTier.LOW,
            Seniority.SENIOR,
            (*_BASE_VIEWS, ReadView.EXPERIMENT_RESULT, ReadView.HYPOTHESIS_STATEMENT),
            (*_SPEAK_IN_MEETINGS, WriteScope.REPLICATION, WriteScope.TASK),
            (*_TALK,),
        ),
        _c(
            "gov.peer_reviewer",
            76,
            "Peer Reviewer",
            Department.INSTITUTIONAL_GOVERNANCE,
            "Structured review before any claim becomes institutional",
            ModelTier.MID,
            Seniority.SENIOR,
            (
                *_BASE_VIEWS,
                ReadView.EXPERIMENT_RESULT,
                ReadView.STRATEGY_EVIDENCE,
                ReadView.OPEN_OBJECTIONS,
            ),
            (*_SPEAK_IN_MEETINGS, WriteScope.OBJECTION, WriteScope.EVIDENCE),
            (*_TALK, ToolScope.MEMORY_SEARCH),
        ),
    )
}


def charters_for_department(department: Department) -> tuple[Charter, ...]:
    return tuple(c for c in CHARTERS.values() if c.department is department)
